
DROP TABLE IF EXISTS pressure;
DROP TABLE IF EXISTS sample;
DROP TABLE IF EXISTS temperature;
DROP TABLE IF EXISTS control_loop;
DROP TABLE IF EXISTS flow;
DROP TABLE IF EXISTS valves;
DROP TABLE IF EXISTS process_log;

